1. Write a Python Program to Add Two Matrices?



In [ ]:
#### Method 1 ####
a = [[1,1],[1,1]]
b = [[2,2],[2,2]]
result = [[0,0],[0,0]]
for i in range(len(a)):
  for j in range(len(b)):
    result[i][j] = a[i][j] + b[i][j]

for r in result:
  print(r)


[3, 3]
[3, 3]


In [ ]:
#### Method 2 Numpy ####
import numpy as np
a = [[1,1],[1,1]]
b = [[2,2],[2,2]]
result = [[0,0],[0,0]]
addition = np.add(a,b)
addition

array([[3, 3],
       [3, 3]])

2. Write a Python Program to Multiply Two Matrices?

In [ ]:
#### Method 1 ####
a = [[1,2],[3,4]]
b = [[1,3],[2,5]]
result = [[0,0],[0,0]]
for i in range( len(a) ):
   for j in range(len(b[0])):
       for k in range(len(b)):
           result[i][j] += a[i][k] * b[k][j]
for r in result:
  print(r)

[5, 13]
[11, 29]


In [ ]:
#### Method 2 Numpy ####
a = [[1,2],[3,4]]
b = [[1,3],[2,5]]
result = [[0,0],[0,0]]
mul = np.dot(a,b)
mul

array([[ 5, 13],
       [11, 29]])

3. Write a Python Program to Transpose a Matrix?

In [ ]:
a = [[1,2],[3,4]]
np.transpose(a)

array([[1, 3],
       [2, 4]])

4. Write a Python Program to Sort Words in Alphabetic Order?

In [ ]:
my_str = input("Enter a string: ")  
words = my_str.split()  
words.sort()  
for word in words:  
  print(word) 

Enter a string: hello world Good morning
Good
hello
morning
world


5. Write a Python Program to Remove Punctuation From a String?

In [ ]:
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
no_pun = ""
my_str = input("Enter a string: ")
for i in my_str:
  if i not in punctuations:
    no_pun = no_pun + i  
print(no_pun)

Enter a string: #@^ ! @( { He&ll%%^^$$o
    Hello
